import { spawn } from "node:child_process";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { materializeWorkspace } from "./materialize";
import { runHarborTrial } from "./adapter";
import type { WorkspaceState } from "@/lib/agent/types";

export type PublishStage =
  | { kind: "status"; stage: string; message: string }
  | { kind: "files"; files: string[] }
  | { kind: "validation"; oracleReward: number | null; nopReward: number | null }
  | { kind: "log"; line: string }
  | { kind: "publish"; repoUrl: string; defaultBranch: string }
  | { kind: "error"; message: string }
  | { kind: "done" };

export type PublishOptions = {
  workspace: WorkspaceState;
  slug: string;
  description: string;
  visibility?: "public" | "private";
  validate?: boolean;
};

function runCommand(
  command: string,
  args: string[],
  cwd: string,
  onLog?: (line: string) => void,
): Promise<{ stdout: string; stderr: string; code: number | null }> {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, { cwd, env: process.env });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (chunk: Buffer) => {
      const text = chunk.toString();
      stdout += text;
      onLog?.(text);
    });
    child.stderr.on("data", (chunk: Buffer) => {
      const text = chunk.toString();
      stderr += text;
      onLog?.(text);
    });
    child.on("error", reject);
    child.on("close", (code) => resolve({ stdout, stderr, code }));
  });
}

async function ensureGhAuth(): Promise<{ ok: boolean; detail: string }> {
  try {
    const result = await runCommand("gh", ["auth", "status"], process.cwd());
    if (result.code === 0) return { ok: true, detail: result.stdout.trim() };
    return { ok: false, detail: result.stderr.trim() || result.stdout.trim() };
  } catch (error) {
    return {
      ok: false,
      detail: error instanceof Error ? error.message : String(error),
    };
  }
}

export async function* publishTaskPack(
  options: PublishOptions,
): AsyncGenerator<PublishStage> {
  const { workspace, slug, description, validate = true } = options;
  const visibility = options.visibility ?? "public";

  const auth = await ensureGhAuth();
  if (!auth.ok) {
    yield {
      kind: "error",
      message: `gh CLI not authenticated. Run 'gh auth login'. Detail: ${auth.detail.slice(0, 240)}`,
    };
    yield { kind: "done" };
    return;
  }

  yield { kind: "status", stage: "materialize", message: "Writing canonical task pack" };

  const tempRoot = await mkdtemp(path.join(tmpdir(), "harbor-publish-"));
  let taskDir = path.join(tempRoot, slug);

  try {
    const { taskDir: writtenDir, files } = await materializeWorkspace({
      workspace,
      destDir: tempRoot,
      taskSlug: slug,
    });
    taskDir = writtenDir;
    yield { kind: "files", files };

    if (validate) {
      yield { kind: "status", stage: "validate-oracle", message: "Running oracle trial" };
      let oracleReward: number | null = null;
      let nopReward: number | null = null;
      try {
        const oracleResult = await runHarborTrial({
          taskDir,
          agent: "oracle",
          onLog: () => {},
        });
        oracleReward = oracleResult.reward;
      } catch (error) {
        yield {
          kind: "log",
          line: `oracle error: ${error instanceof Error ? error.message : String(error)}`,
        };
      }

      yield { kind: "status", stage: "validate-nop", message: "Running nop trial" };
      try {
        const nopResult = await runHarborTrial({
          taskDir,
          agent: "nop",
          onLog: () => {},
        });
        nopReward = nopResult.reward;
      } catch (error) {
        yield {
          kind: "log",
          line: `nop error: ${error instanceof Error ? error.message : String(error)}`,
        };
      }

      yield { kind: "validation", oracleReward, nopReward };
    }

    yield {
      kind: "status",
      stage: "git-init",
      message: "Initializing repo and committing scaffold",
    };

    const gitInit = await runCommand("git", ["init", "-b", "main"], taskDir);
    if (gitInit.code !== 0) {
      yield { kind: "error", message: `git init failed: ${gitInit.stderr.trim()}` };
      yield { kind: "done" };
      return;
    }

    const readmePath = path.join(taskDir, "README.md");
    await writeFile(
      readmePath,
      `# ${slug}\n\n${description}\n\nGenerated by Harbor Eval Studio.\n`,
      "utf8",
    );

    const gitAdd = await runCommand("git", ["add", "-A"], taskDir);
    if (gitAdd.code !== 0) {
      yield { kind: "error", message: `git add failed: ${gitAdd.stderr.trim()}` };
      yield { kind: "done" };
      return;
    }

    const gitCommit = await runCommand(
      "git",
      ["commit", "-m", "Initial Harbor task pack"],
      taskDir,
    );
    if (gitCommit.code !== 0) {
      yield {
        kind: "error",
        message: `git commit failed: ${gitCommit.stderr.trim() || gitCommit.stdout.trim()}`,
      };
      yield { kind: "done" };
      return;
    }

    yield {
      kind: "status",
      stage: "gh-create",
      message: `Creating GitHub repo (${visibility})`,
    };

    const repoArgs = [
      "repo",
      "create",
      slug,
      visibility === "public" ? "--public" : "--private",
      "--source=.",
      "--remote=origin",
      "--push",
      "--description",
      description,
    ];

    const repoCreate = await runCommand("gh", repoArgs, taskDir);
    if (repoCreate.code !== 0) {
      yield {
        kind: "error",
        message: `gh repo create failed: ${repoCreate.stderr.trim() || repoCreate.stdout.trim()}`,
      };
      yield { kind: "done" };
      return;
    }

    const urlMatch = repoCreate.stdout.match(/https:\/\/github\.com\/[^\s]+/);
    const repoUrl = urlMatch ? urlMatch[0] : repoCreate.stdout.trim();

    yield {
      kind: "publish",
      repoUrl,
      defaultBranch: "main",
    };
    yield { kind: "done" };
  } catch (error) {
    yield {
      kind: "error",
      message: error instanceof Error ? error.message : String(error),
    };
    yield { kind: "done" };
  } finally {
    try {
      await rm(tempRoot, { recursive: true, force: true });
    } catch {
      // ignore
    }
  }
}
