export type TaskTomlOptions = {
  slug: string;
  org?: string;
  description?: string;
  difficulty?: string;
};

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
}

export function harborTaskId(slug: string, org?: string) {
  const taskSlug = slugify(slug) || "eval-task";
  const taskOrg = (org ?? process.env.HARBOR_PUBLISH_ORG ?? "local").trim();
  return `${taskOrg}/${taskSlug}`;
}

/** Build Harbor-valid task.toml with required [task] package block. */
export function buildTaskToml(options: TaskTomlOptions): string {
  const taskSlug = slugify(options.slug) || "eval-task";
  const taskOrg = (options.org ?? process.env.HARBOR_PUBLISH_ORG ?? "local").trim();
  const description =
    options.description?.replace(/"/g, '\\"') ??
    "Harbor eval task generated by Harbor Eval Studio.";
  const difficulty = options.difficulty ?? "hard";

  return `[task]
id = "${taskOrg}/${taskSlug}"
description = "${description}"

[metadata]
difficulty = "${difficulty}"

[environment]
cpus = 1
memory_mb = 4096
storage_mb = 10240

[agent]
timeout_sec = 1800

[verifier]
timeout_sec = 900
`;
}

/** Ensure workspace task.toml has a valid [task] block; merge metadata if LLM omitted it. */
export function normalizeTaskTomlContent(
  existing: string | undefined,
  options: TaskTomlOptions,
): string {
  const canonical = buildTaskToml(options);
  if (!existing?.trim()) return canonical;

  if (/\[task\]/i.test(existing) && /id\s*=\s*["'][^"']+\/[^"']+["']/i.test(existing)) {
    return existing;
  }

  const taskBlock = buildTaskToml(options).split("\n\n")[0];
  return `${taskBlock}\n\n${existing.trim()}\n`;
}
