import { publishTaskPack } from "@/lib/harbor/connector";
import { buildDemoWorkspace } from "@/lib/agent/seed-workspace";
import type { Artifact, WorkspaceState } from "@/lib/agent/types";

export const runtime = "nodejs";
export const maxDuration = 600;

type RequestBody = {
  slug?: string;
  description?: string;
  validate?: boolean;
  visibility?: "public" | "private";
  workspace?: {
    phase?: WorkspaceState["phase"];
    artifacts?: Artifact[];
  };
};

export async function POST(request: Request) {
  let body: RequestBody = {};
  try {
    body = (await request.json()) as RequestBody;
  } catch {
    body = {};
  }

  const workspace = buildDemoWorkspace();
  if (body.workspace?.phase) workspace.phase = body.workspace.phase;
  if (body.workspace?.artifacts) {
    for (const artifact of body.workspace.artifacts) {
      workspace.artifacts[artifact.path] = artifact;
    }
  }

  const rawSlug = (body.slug ?? "eval-task").trim();
  const slug = rawSlug
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60) || "eval-task";

  const description =
    (body.description ?? "Harbor eval task generated by Harbor Eval Studio.").slice(0, 280);
  const validate = body.validate ?? false;
  const visibility = body.visibility ?? "public";

  const encoder = new TextEncoder();

  const stream = new ReadableStream<Uint8Array>({
    async start(controller) {
      try {
        for await (const event of publishTaskPack({
          workspace,
          slug,
          description,
          validate,
          visibility,
        })) {
          controller.enqueue(
            encoder.encode(`data: ${JSON.stringify(event)}\n\n`),
          );
        }
      } catch (error) {
        controller.enqueue(
          encoder.encode(
            `data: ${JSON.stringify({
              kind: "error",
              message: error instanceof Error ? error.message : "publish failed",
            })}\n\n`,
          ),
        );
      } finally {
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache, no-transform",
      Connection: "keep-alive",
    },
  });
}
