"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useFocusTrap } from "@/lib/hooks/use-focus-trap";
import { CheckCircle2, ExternalLink, Loader2, Package, XCircle, X } from "lucide-react";
import { useWorkbench } from "@/lib/workbench/store";
import { cn } from "@/lib/utils";

type StageRow = {
  key: string;
  label: string;
  state: "pending" | "active" | "done" | "error" | "skipped";
  detail?: string;
};

function buildInitialStages(validate: boolean, exportGitHub: boolean): StageRow[] {
  const rows: StageRow[] = [
    { key: "materialize", label: "Materialize task pack", state: "pending" },
  ];
  if (validate) {
    rows.push(
      { key: "validate-oracle", label: "Validate oracle = 1", state: "pending" },
      { key: "validate-nop", label: "Validate nop = 0", state: "pending" },
    );
  }
  rows.push(
    { key: "harbor-task-update", label: "Update Harbor task package", state: "pending" },
    { key: "harbor-publish", label: "Publish to Harbor registry", state: "pending" },
  );
  if (exportGitHub) {
    rows.push(
      { key: "git-init", label: "Initialize git", state: "pending" },
      { key: "gh-create", label: "Export to GitHub", state: "pending" },
    );
  }
  return rows;
}

export function PublishDialog() {
  const open = useWorkbench((s) => s.publishOpen);
  if (!open) return null;
  return <PublishDialogBody />;
}

function PublishDialogBody() {
  const setOpen = useWorkbench((s) => s.setPublishOpen);
  const workspace = useWorkbench((s) => s.workspace);
  const envStatus = useWorkbench((s) => s.envStatus);
  const trapRef = useFocusTrap<HTMLDivElement>(true);

  useEffect(() => {
    const handler = (e: KeyboardEvent) => { if (e.key === "Escape") setOpen(false); };
    document.addEventListener("keydown", handler);
    return () => document.removeEventListener("keydown", handler);
  }, [setOpen]);

  const defaultSlug = useMemo(() => {
    return workspace.projectName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60) || "eval-task";
  }, [workspace.projectName]);

  const defaultExportGitHub = envStatus?.publishTarget === "github" || envStatus?.publishTarget === "both";

  const [slug, setSlug] = useState(defaultSlug);
  const [description, setDescription] = useState("Harbor eval task generated by Harbor Eval Studio.");
  const [validate, setValidate] = useState(true);
  const [exportGitHub, setExportGitHub] = useState(defaultExportGitHub);
  const [visibility, setVisibility] = useState<"public" | "private">("public");
  const [running, setRunning] = useState(false);
  const [stages, setStages] = useState<StageRow[]>(() => buildInitialStages(true, defaultExportGitHub));
  const [files, setFiles] = useState<string[]>([]);
  const [registryRef, setRegistryRef] = useState<string | null>(null);
  const [registryUrl, setRegistryUrl] = useState<string | null>(null);
  const [repoUrl, setRepoUrl] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const controllerRef = useRef<AbortController | null>(null);

  useEffect(() => () => { controllerRef.current?.abort(); }, []);

  const markStage = (key: string, state: StageRow["state"], detail?: string) => {
    setStages((rows) => rows.map((row) => row.key === key ? { ...row, state, detail: detail ?? row.detail } : row));
  };

  const publish = async () => {
    if (running) return;
    setRunning(true);
    setRegistryRef(null);
    setRegistryUrl(null);
    setRepoUrl(null);
    setErrorMessage(null);
    setStages(buildInitialStages(validate, exportGitHub));

    controllerRef.current?.abort();
    const controller = new AbortController();
    controllerRef.current = controller;

    try {
      const response = await fetch("/api/publish", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          slug, description, validate, visibility, exportToGitHub: exportGitHub,
          workspace: { phase: workspace.phase, artifacts: Object.values(workspace.artifacts) },
        }),
        signal: controller.signal,
      });

      if (!response.body) throw new Error("No response body");

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = "";

      while (true) {
        const { value, done } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const events = buffer.split("\n\n");
        buffer = events.pop() ?? "";

        for (const raw of events) {
          if (!raw.startsWith("data: ")) continue;
          let event: Record<string, unknown>;
          try { event = JSON.parse(raw.slice(6)); } catch { continue; }

          if (event.kind === "status" && event.stage) {
            markStage(event.stage as string, "active", event.message as string);
          } else if (event.kind === "files" && event.files) {
            setFiles(event.files as string[]);
            markStage("materialize", "done", `${(event.files as string[]).length} files`);
          } else if (event.kind === "validation") {
            markStage("validate-oracle", event.oracleReward === 1 ? "done" : "error", `reward = ${event.oracleReward ?? "?"}`);
            markStage("validate-nop", event.nopReward === 0 ? "done" : "error", `reward = ${event.nopReward ?? "?"}`);
          } else if (event.kind === "publish") {
            markStage("harbor-task-update", "done");
            markStage("harbor-publish", "done", (event.registryRef as string) ?? undefined);
            if (event.repoUrl) {
              markStage("git-init", "done");
              markStage("gh-create", "done", event.repoUrl as string);
            }
            if (event.registryRef) setRegistryRef(event.registryRef as string);
            if (event.registryUrl) setRegistryUrl(event.registryUrl as string);
            if (event.repoUrl) setRepoUrl(event.repoUrl as string);
          } else if (event.kind === "error") {
            setErrorMessage((event.message as string) ?? "Publish failed");
            setStages((rows) => rows.map((row) => row.state === "active" ? { ...row, state: "error" } : row));
          } else if (event.kind === "done") {
            setStages((rows) => rows.map((row) => row.state === "active" ? { ...row, state: "done" } : row));
          }
        }
      }
    } catch (err) {
      if (!(err instanceof DOMException && err.name === "AbortError")) {
        setErrorMessage(err instanceof Error ? err.message : String(err));
      }
    } finally {
      controllerRef.current = null;
      setRunning(false);
    }
  };

  const org = envStatus?.harborPublishOrg;

  return (
    <div className="fixed inset-0 z-50 bg-black/20 backdrop-blur-sm" onClick={() => !running && setOpen(false)}>
      <div
        ref={trapRef}
        role="dialog"
        aria-modal="true"
        className="mx-auto mt-[10vh] w-[min(640px,94vw)] overflow-hidden rounded-2xl border border-[var(--border-strong)] bg-white shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between border-b border-[var(--border)] px-6 py-5">
          <div>
            <h2 className="text-[17px] font-semibold tracking-tight">Publish to Harbor</h2>
            <p className="mt-1 text-[13px] text-[var(--fg-muted)]">Registry publish{exportGitHub ? " + optional GitHub export" : ""}</p>
          </div>
          <button type="button" onClick={() => !running && setOpen(false)} className="rounded-lg p-1.5 text-[var(--fg-muted)] hover:bg-[var(--bg-hover)] transition-colors">
            <X className="h-4 w-4" />
          </button>
        </div>

        <div className="grid gap-5 px-6 py-5 md:grid-cols-[1fr_200px]">
          <div className="space-y-4">
            <label className="block">
              <span className="text-[12px] font-medium text-[var(--fg-secondary)]">Task slug</span>
              <input value={slug} onChange={(e) => setSlug(e.target.value)} disabled={running} className="mt-1.5 w-full rounded-lg border border-[var(--border)] bg-white px-3 py-2.5 text-[14px] outline-none focus:border-[var(--accent)] focus:shadow-[0_0_0_3px_var(--accent-soft)] transition-all" />
            </label>
            <label className="block">
              <span className="text-[12px] font-medium text-[var(--fg-secondary)]">Description</span>
              <textarea value={description} onChange={(e) => setDescription(e.target.value)} disabled={running} rows={2} className="mt-1.5 w-full resize-none rounded-lg border border-[var(--border)] bg-white px-3 py-2.5 text-[14px] outline-none focus:border-[var(--accent)] focus:shadow-[0_0_0_3px_var(--accent-soft)] transition-all" />
            </label>
            <div className="flex flex-wrap items-center gap-4 text-[13px] text-[var(--fg-muted)]">
              <label className="inline-flex items-center gap-2"><input type="checkbox" checked={validate} onChange={(e) => setValidate(e.target.checked)} disabled={running} className="rounded" /> Validate oracle/nop</label>
              <label className="inline-flex items-center gap-2"><input type="checkbox" checked={exportGitHub} onChange={(e) => setExportGitHub(e.target.checked)} disabled={running} className="rounded" /> Also push to GitHub</label>
              <label className="inline-flex items-center gap-2"><input type="radio" checked={visibility === "public"} onChange={() => setVisibility("public")} disabled={running} /> Public</label>
              <label className="inline-flex items-center gap-2"><input type="radio" checked={visibility === "private"} onChange={() => setVisibility("private")} disabled={running} /> Private</label>
            </div>
          </div>
          <aside className="rounded-xl bg-[var(--bg-muted)] p-3 text-[12px] text-[var(--fg-muted)] leading-relaxed space-y-2">
            <p>Requires <span className="mono font-medium">harbor auth login</span> and <span className="mono font-medium">HARBOR_PUBLISH_ORG</span>.</p>
            {org ? <p className="mono text-[11px]">org/{slug} → {org}/{slug}</p> : <p className="text-[var(--amber)]">Set HARBOR_PUBLISH_ORG in .env.local</p>}
            {exportGitHub && <p>Optional export needs <span className="mono font-medium">gh auth login</span>.</p>}
          </aside>
        </div>

        <div className="border-t border-[var(--border)] bg-[var(--bg-surface)] px-6 py-5 space-y-2.5">
          {stages.map((stage) => (
            <div key={stage.key} className="flex items-center justify-between gap-3 text-[13px]">
              <span className={cn("flex items-center gap-2.5",
                stage.state === "done" && "text-[var(--green)]",
                stage.state === "error" && "text-[var(--red)]",
                stage.state === "active" && "text-[var(--fg)]",
                stage.state === "pending" && "text-[var(--fg-faint)]",
                stage.state === "skipped" && "text-[var(--fg-faint)]",
              )}>
                {stage.state === "done" && <CheckCircle2 className="h-4 w-4" />}
                {stage.state === "error" && <XCircle className="h-4 w-4" />}
                {stage.state === "active" && <Loader2 className="h-4 w-4 animate-spin" />}
                {stage.state === "pending" && <span className="h-4 w-4 rounded-full border border-[var(--border-strong)]" />}
                {stage.label}
              </span>
              {stage.detail && <span className="mono truncate text-right text-[12px] text-[var(--fg-faint)] max-w-[240px]">{stage.detail}</span>}
            </div>
          ))}

          {files.length > 0 && (
            <div className="mt-3 rounded-xl border border-[var(--border)] bg-white p-3">
              <p className="text-[11px] font-semibold uppercase tracking-wider text-[var(--fg-muted)]">Scaffold ({files.length} files)</p>
              <div className="mt-2 max-h-32 overflow-y-auto text-[12px] mono text-[var(--fg-secondary)]">
                {files.map((f) => <div key={f} className="truncate">{f}</div>)}
              </div>
            </div>
          )}

          {errorMessage && (
            <div className="mt-3 rounded-xl border border-[var(--red-soft)] bg-[var(--red-soft)] p-3 text-[13px] text-[var(--red)]">{errorMessage}</div>
          )}

          {registryUrl && (
            <div className="mt-3 flex items-center justify-between gap-3 rounded-xl border border-[var(--green-soft)] bg-[var(--green-soft)] px-4 py-3 text-[13px] text-[var(--green)]">
              <span className="truncate">
                <span className="font-medium">{registryRef ?? "Published"}</span>
                <span className="block mono text-[11px] opacity-80 truncate">{registryUrl}</span>
              </span>
              <a href={registryUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 rounded-lg bg-[var(--green)] px-3 py-1.5 text-[12px] font-medium text-white shrink-0">
                Hub <ExternalLink className="h-3 w-3" />
              </a>
            </div>
          )}

          {repoUrl && (
            <div className="mt-2 flex items-center justify-between gap-3 rounded-xl border border-[var(--border)] bg-white px-4 py-3 text-[13px]">
              <span className="mono truncate text-[var(--fg-secondary)]">{repoUrl}</span>
              <a href={repoUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 rounded-lg border border-[var(--border)] px-3 py-1.5 text-[12px] font-medium shrink-0">
                GitHub <ExternalLink className="h-3 w-3" />
              </a>
            </div>
          )}
        </div>

        <div className="flex items-center justify-between gap-3 border-t border-[var(--border)] px-6 py-4">
          <p className="text-[12px] text-[var(--fg-muted)]">
            {org ? <span className="mono">{org}/{slug}@latest</span> : "Configure HARBOR_PUBLISH_ORG to publish"}
          </p>
          <div className="flex items-center gap-2">
            <button type="button" onClick={() => setOpen(false)} disabled={running} className="rounded-lg border border-[var(--border)] px-4 py-2 text-[13px] text-[var(--fg-secondary)] hover:bg-[var(--bg-hover)] transition-colors">
              Close
            </button>
            <button
              type="button"
              onClick={() => void publish()}
              disabled={running || !slug.trim()}
              className={cn(
                "inline-flex items-center gap-2 rounded-lg bg-[var(--accent)] px-5 py-2 text-[13px] font-medium text-white transition-opacity",
                (running || !slug.trim()) && "opacity-40",
              )}
            >
              {running ? <Loader2 className="h-4 w-4 animate-spin" /> : <Package className="h-4 w-4" />}
              {running ? "Publishing..." : "Publish"}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
