"use client";

import { useMemo, useState } from "react";
import { AnimatePresence, motion } from "motion/react";
import {
  CheckCircle2,
  ExternalLink,
  GitBranch,
  Loader2,
  ShieldAlert,
  Sparkles,
  X,
} from "lucide-react";
import { useWorkbench } from "@/lib/workbench/store";
import { cn } from "@/lib/utils";

type StageRow = {
  key: string;
  label: string;
  state: "pending" | "active" | "done" | "error";
  detail?: string;
};

const INITIAL_STAGES: StageRow[] = [
  { key: "materialize", label: "Materialize task pack", state: "pending" },
  { key: "validate-oracle", label: "Validate oracle = 1", state: "pending" },
  { key: "validate-nop", label: "Validate nop = 0", state: "pending" },
  { key: "git-init", label: "Initialize git", state: "pending" },
  { key: "gh-create", label: "Create GitHub repo + push", state: "pending" },
];

export function PublishDialog() {
  const open = useWorkbench((s) => s.publishOpen);
  return (
    <AnimatePresence>{open && <PublishDialogBody />}</AnimatePresence>
  );
}

function PublishDialogBody() {
  const setOpen = useWorkbench((s) => s.setPublishOpen);
  const workspace = useWorkbench((s) => s.workspace);

  const defaultSlug = useMemo(() => {
    return workspace.projectName
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "eval-task";
  }, [workspace.projectName]);

  const [slug, setSlug] = useState(defaultSlug);
  const [description, setDescription] = useState(
    "Harbor eval task generated by Harbor Eval Studio.",
  );
  const [validate, setValidate] = useState(true);
  const [visibility, setVisibility] = useState<"public" | "private">("public");
  const [running, setRunning] = useState(false);
  const [stages, setStages] = useState<StageRow[]>(INITIAL_STAGES);
  const [files, setFiles] = useState<string[]>([]);
  const [repoUrl, setRepoUrl] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const markStage = (
    key: string,
    state: StageRow["state"],
    detail?: string,
  ) => {
    setStages((rows) =>
      rows.map((row) =>
        row.key === key ? { ...row, state, detail: detail ?? row.detail } : row,
      ),
    );
  };

  const publish = async () => {
    if (running) return;
    setRunning(true);
    setRepoUrl(null);
    setErrorMessage(null);
    setStages(
      INITIAL_STAGES.map((row) =>
        validate || (row.key !== "validate-oracle" && row.key !== "validate-nop")
          ? { ...row, state: "pending" }
          : { ...row, state: "done", detail: "skipped" },
      ),
    );

    try {
      const response = await fetch("/api/publish", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          slug,
          description,
          validate,
          visibility,
          workspace: {
            phase: workspace.phase,
            artifacts: Object.values(workspace.artifacts),
          },
        }),
      });

      if (!response.body) {
        throw new Error("No response body");
      }

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = "";

      while (true) {
        const { value, done } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const events = buffer.split("\n\n");
        buffer = events.pop() ?? "";

        for (const raw of events) {
          if (!raw.startsWith("data: ")) continue;
          const payload = raw.slice("data: ".length);
          let event: {
            kind: string;
            stage?: string;
            message?: string;
            files?: string[];
            oracleReward?: number | null;
            nopReward?: number | null;
            repoUrl?: string;
            line?: string;
          };
          try {
            event = JSON.parse(payload);
          } catch {
            continue;
          }

          if (event.kind === "status" && event.stage) {
            markStage(event.stage, "active", event.message);
          } else if (event.kind === "files" && event.files) {
            setFiles(event.files);
            markStage("materialize", "done", `${event.files.length} files`);
          } else if (event.kind === "validation") {
            markStage(
              "validate-oracle",
              event.oracleReward === 1 ? "done" : "error",
              `reward = ${event.oracleReward ?? "?"}`,
            );
            markStage(
              "validate-nop",
              event.nopReward === 0 ? "done" : "error",
              `reward = ${event.nopReward ?? "?"}`,
            );
          } else if (event.kind === "publish" && event.repoUrl) {
            markStage("git-init", "done");
            markStage("gh-create", "done", event.repoUrl);
            setRepoUrl(event.repoUrl);
          } else if (event.kind === "error") {
            setErrorMessage(event.message ?? "Publish failed");
            setStages((rows) =>
              rows.map((row) =>
                row.state === "active" ? { ...row, state: "error" } : row,
              ),
            );
          }
        }
      }
    } catch (error) {
      setErrorMessage(error instanceof Error ? error.message : String(error));
    } finally {
      setRunning(false);
    }
  };

  return (
    <motion.div
      key="publish-backdrop"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.18 }}
      className="fixed inset-0 z-50 bg-[rgba(20,20,20,0.32)] backdrop-blur-sm"
      onClick={() => !running && setOpen(false)}
    >
      <motion.div
        key="publish-card"
        initial={{ opacity: 0, y: 16, scale: 0.97 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        exit={{ opacity: 0, y: 12, scale: 0.97 }}
        transition={{ type: "spring", stiffness: 320, damping: 32 }}
        className="mx-auto mt-[10vh] w-[min(720px,94vw)] overflow-hidden rounded-2xl border border-[var(--hairline-strong)] bg-[var(--paper-pure)] shadow-[var(--shadow-pop)]"
        onClick={(event) => event.stopPropagation()}
      >
            <div className="flex items-center justify-between border-b border-[var(--hairline)] px-6 py-4">
              <div className="flex items-center gap-2">
                <span className="flex h-7 w-7 items-center justify-center rounded-full bg-[var(--ink)] text-[var(--paper-pure)]">
                  <GitBranch className="h-3.5 w-3.5" />
                </span>
                <div>
                  <p className="eyebrow">Publish</p>
                  <h2 className="mt-1 text-[14px] font-semibold tracking-[-0.01em]">
                    Push Harbor task pack to a new GitHub repo
                  </h2>
                </div>
              </div>
              <button
                type="button"
                onClick={() => !running && setOpen(false)}
                className="rounded-full p-1 text-[var(--ink-muted)] hover:bg-[var(--cream-soft)] hover:text-[var(--ink)]"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            <div className="grid gap-5 px-6 py-5 md:grid-cols-[1fr_220px]">
              <div className="space-y-3">
                <label className="block">
                  <span className="eyebrow">Repository slug</span>
                  <input
                    value={slug}
                    onChange={(event) => setSlug(event.target.value)}
                    disabled={running}
                    className="mt-1.5 w-full rounded-lg border border-[var(--hairline-strong)] bg-[var(--paper)] px-3 py-2 text-[13px] outline-none focus:border-[var(--ink)]/30"
                  />
                </label>
                <label className="block">
                  <span className="eyebrow">Description</span>
                  <textarea
                    value={description}
                    onChange={(event) => setDescription(event.target.value)}
                    disabled={running}
                    rows={2}
                    className="mt-1.5 w-full rounded-lg border border-[var(--hairline-strong)] bg-[var(--paper)] px-3 py-2 text-[13px] outline-none focus:border-[var(--ink)]/30"
                  />
                </label>
                <div className="flex items-center gap-4 text-[12px] text-[var(--ink-muted)]">
                  <label className="inline-flex items-center gap-2">
                    <input
                      type="checkbox"
                      checked={validate}
                      onChange={(event) => setValidate(event.target.checked)}
                      disabled={running}
                    />
                    Validate oracle + nop before push
                  </label>
                  <label className="inline-flex items-center gap-2">
                    <input
                      type="radio"
                      checked={visibility === "public"}
                      onChange={() => setVisibility("public")}
                      disabled={running}
                    />
                    Public
                  </label>
                  <label className="inline-flex items-center gap-2">
                    <input
                      type="radio"
                      checked={visibility === "private"}
                      onChange={() => setVisibility("private")}
                      disabled={running}
                    />
                    Private
                  </label>
                </div>
              </div>

              <aside className="rounded-xl border border-[var(--hairline)] bg-[var(--cream)] p-4 text-[11.5px] text-[var(--ink-muted)]">
                <p className="eyebrow">Heads up</p>
                <p className="mt-2 leading-5">
                  Requires <span className="mono">gh</span> authenticated locally. We create a
                  fresh repo per task. Validation requires the <span className="mono">harbor</span> CLI.
                </p>
              </aside>
            </div>

            <div className="border-t border-[var(--hairline)] bg-[var(--paper)] px-6 py-4">
              <div className="space-y-2">
                {stages.map((stage) => {
                  const tone =
                    stage.state === "done"
                      ? "text-[var(--status-green)]"
                      : stage.state === "error"
                        ? "text-[var(--status-red)]"
                        : stage.state === "active"
                          ? "text-[var(--ink)]"
                          : "text-[var(--ink-faint)]";
                  return (
                    <div
                      key={stage.key}
                      className="flex items-center justify-between gap-3 text-[12.5px]"
                    >
                      <span className={cn("flex items-center gap-2", tone)}>
                        {stage.state === "done" ? (
                          <CheckCircle2 className="h-3.5 w-3.5" />
                        ) : stage.state === "error" ? (
                          <ShieldAlert className="h-3.5 w-3.5" />
                        ) : stage.state === "active" ? (
                          <Loader2 className="h-3.5 w-3.5 animate-spin" />
                        ) : (
                          <Sparkles className="h-3.5 w-3.5" />
                        )}
                        {stage.label}
                      </span>
                      {stage.detail && (
                        <span className="mono truncate text-right text-[11px] text-[var(--ink-faint)]">
                          {stage.detail}
                        </span>
                      )}
                    </div>
                  );
                })}
              </div>

              {files.length > 0 && (
                <div className="mt-4 rounded-xl border border-[var(--hairline)] bg-[var(--paper-pure)] p-3">
                  <p className="eyebrow">Scaffold ({files.length} files)</p>
                  <div className="mt-2 max-h-40 overflow-y-auto pr-1 text-[11.5px] text-[var(--ink-soft)]">
                    {files.map((file) => (
                      <div key={file} className="mono truncate">
                        {file}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {errorMessage && (
                <div className="mt-4 rounded-lg border border-[var(--status-red-soft)] bg-[var(--status-red-soft)] p-3 text-[12px] text-[var(--status-red)]">
                  {errorMessage}
                </div>
              )}

              {repoUrl && (
                <div className="mt-4 flex items-center justify-between gap-3 rounded-lg border border-[var(--status-green-soft)] bg-[var(--status-green-soft)] px-3 py-2 text-[12px] text-[var(--status-green)]">
                  <span className="mono truncate">{repoUrl}</span>
                  <a
                    href={repoUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="inline-flex items-center gap-1 rounded-full bg-[var(--status-green)] px-2.5 py-1 text-[11px] font-medium text-white"
                  >
                    Open <ExternalLink className="h-3 w-3" />
                  </a>
                </div>
              )}
            </div>

            <div className="flex items-center justify-between gap-3 border-t border-[var(--hairline)] px-6 py-4">
              <p className="text-[11.5px] text-[var(--ink-muted)]">
                A new repo will be created at <span className="mono">github.com/&lt;your account&gt;/{slug}</span>.
              </p>
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={() => setOpen(false)}
                  disabled={running}
                  className="rounded-full border border-[var(--hairline-strong)] bg-[var(--paper-pure)] px-3 py-1.5 text-[12px] text-[var(--ink-soft)] hover:bg-[var(--cream-soft)]"
                >
                  Close
                </button>
                <button
                  type="button"
                  onClick={() => void publish()}
                  disabled={running || !slug.trim()}
                  className={cn(
                    "inline-flex items-center gap-1.5 rounded-full bg-[var(--ink)] px-4 py-2 text-[12.5px] font-medium text-[var(--paper-pure)] transition-transform hover:-translate-y-0.5",
                    (running || !slug.trim()) && "opacity-50 hover:translate-y-0",
                  )}
                >
                  {running ? (
                    <Loader2 className="h-3.5 w-3.5 animate-spin" />
                  ) : (
                    <GitBranch className="h-3.5 w-3.5" />
                  )}
                  {running ? "Publishing…" : "Publish to GitHub"}
                </button>
              </div>
            </div>
      </motion.div>
    </motion.div>
  );
}
